@php
	$pageTitle = $pageTitle ?? 'Subscription – Aesort';
	$currentPage = $currentPage ?? 'subscription';
@endphp
@include('include.header')
<!-- Page Header Start -->
<div class="page-header parallaxie">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <!-- Page Header Box Start -->
                <div class="page-header-box">
                    <h1 class="text-anime">Subscription</h1>
                    <nav class="wow fadeInUp" data-wow-delay="0.25s">
                        <ol class="breadcrumb">
							<li class="breadcrumb-item"><a href="{{ route('home') }}">Home</a></li>
                            <li class="breadcrumb-separator">/</li>
                            <li class="breadcrumb-item active" aria-current="page">Subscription</li>
                        </ol>
                    </nav>
                </div>
                <!-- Page Header Box End -->
            </div>
        </div>
    </div>
</div>
<!-- Page Header End -->

<!-- Services List Page Start -->
<div class="page-services">
    <div class="container">
        <div class="row">
          	<!-- Pricing Layout 2 Start -->
	<div class="pricing-layout2" id="subscription">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<!-- Section Title Start -->
					<div class="section-title">
						<h3 class="wow fadeInUp">Our Pricing</h3>
						<h2 class="text-anime">Choose Your Best Offer</h2>
					</div>
					<!-- Section Title End -->
				</div>
			</div>

		<div class="row">
				<div class="col-lg-4">
					<!-- Pricing Item Box Start -->
					<div class="pricing-item2 wow fadeInUp" data-wow-delay="0.25s">
						<div class="package-icon-box">
							<img src="assets/images/icon-pricing-1.svg" alt="">
						</div>

						<div class="price-header">
							<h2>Basic</h2>
							
						</div>

						<div class="price-body">
							<ul>
								<li>$2,499 per month for users with up to 2,000 sq ft of commercial space</li>
								<li>$5,999 per month for users with more than 2,000 sq. ft. up to 5,000 of sq. ft. commercial space.</li>
								<li>Custom Quote for users with more than 5,000 of sq ft commercial space.</li>
								
								
							</ul>
						</div>

						<!-- <div class="price-buy-button">
							<a href="{{ route('contact') }}" class="btn-default">Subscribe</a>
						</div>						 -->
					</div>
					<!-- Pricing Item Box End -->
				</div>

				<div class="col-lg-4">
					<!-- Pricing Item Box Start -->
					<div class="pricing-item2 wow fadeInUp" data-wow-delay="0.5s">
						<div class="package-icon-box">
							<img src="assets/images/icon-pricing-2.svg" alt="">
						</div>

						<div class="price-header">
							<h2>Standard</h2>
							
						</div>

						<div class="price-body">
							<ul>
								<li>$399 per month for users with up to 2,000 sq. ft. of commercial space.</li>
								<li>$599 per month for users with more than 2,000 sq. ft. up to 5,000 of sq. ft. commercial space.</li>
								<li>Custom Quote for users with more than 5,000 of sq. ft. commercial space.</li>
								
								
							</ul>
						</div>

						<!-- <div class="price-buy-button">
							<a href="{{ route('contact') }}" class="btn-default">Subscribe</a>
						</div>						 -->
					</div>
					<!-- Pricing Item Box End -->
				</div>

				<div class="col-lg-4">
					<!-- Pricing Item Box Start -->
					<div class="pricing-item2 wow fadeInUp" data-wow-delay="0.75s">
						<div class="package-icon-box">
							<img src="assets/images/icon-pricing-3.svg" alt="">
						</div>

						<div class="price-header">
							<h2>Premium</h2>
							
						</div>

						<div class="price-body">
							<ul>
								<li>Data Insights and Analytics ($699/ report)</li>
								<li>This model includes data insights and analytics generated by the system for details into energy consumption patterns, cost-saving opportunities, and environmental impact assessments.</li>
								
								
								
							</ul>
						</div>

						<!-- <div class="price-buy-button">
							<a href="{{ route('contact') }}" class="btn-default">Subscribe</a>
						</div>						 -->
					</div>
					<!-- Pricing Item Box End -->
				</div>
			</div>
		</div>
	</div>
	<!-- Pricing Layout 2 End -->
        </div>
    </div>
</div>
<!-- Services List Page End -->



<!-- Infobar Section End -->
<!-- Why Choose us Section Start -->

<!-- Why Choose us Section End -->

<!-- Footer Ticker Start -->
<div class="footer-ticker">
    <div class="scrolling-ticker">
        <div class="scrolling-ticker-box">
            <div class="scrolling-content">
          <span>Optimize Your Energy Usage</span>
<span>Maximize Commercial Savings</span>
<span>Powering a Greener Future</span>
<span>Smart Energy, Smart Business</span>
<span>Reliable 24×7 Monitoring</span>

            </div>

            <div class="scrolling-content">
            <span>Optimize Your Energy Usage</span>
<span>Maximize Commercial Savings</span>
<span>Powering a Greener Future</span>
<span>Smart Energy, Smart Business</span>
<span>Reliable 24×7 Monitoring</span>

            </div>
        </div>
    </div>
</div>
<!-- Footer Ticker End -->

@include('include.footer')